# Generated by Django 2.1.1 on 2019-08-28 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='порядковый номер')),
                ('name', models.CharField(max_length=15, verbose_name='название поля')),
                ('width', models.IntegerField(verbose_name='ширина поля')),
            ],
            options={
                'verbose_name': 'поле',
                'verbose_name_plural': 'поля',
            },
        ),
        migrations.CreateModel(
            name='TableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField(path='F:\\Python_projects\\DJ-5\\creating-project\\application', verbose_name='путь к файлу')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
            },
        ),
        migrations.AddField(
            model_name='tablefield',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table.TableFile'),
        ),
    ]
